---
# tasks file for roles/mysql57
# change password
#- name: copy .my.cnf file with root password credentials
#  template: src=templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
#  tags:
#    - mysql_change_password

- name: Change Root Password
  mysql_user:
#    login_user: root
#    login_password: "{{ current_mysql_password }}"
    name: root
    host: "{{ item }}"
    password: "{{ mysql_password }}"
#    password: 'password'
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: yes
  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
    - localhost
  tags:
    - mysql_change_password

- name: copy .my.cnf file with root password credentials
  template: src=templates/my.cnf_change.j2 dest=/root/.my.cnf owner=root
  tags:
    - mysql_change_password
